services:
  - type: web
    name: telegram-rp-bot
    env: python
    buildCommand: ""
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
    pythonVersion: 3.10.13
